begin_remark: coding RZ canonical subject criteria. 16/07/15: add cols 12-13 for nominal subjects only. 21/07/15: clean up nom-args.
end_remark
node: IP*
remove_nodes: t
nodes_only: t
ignore_nodes: \**|CODE|ID|'|\"|,|/|\.|FRAG|X|COMMENT|LB|BREAK|HL|LL|*PRN*|NEG|*VOC*

coding_query: 

// SBJ - position of subject in subordinate clauses, canonical or otherwise
// CODING is the first node of the clause, so we're looking from the 2nd node on

// 10: all subjects, all clauses
// '10c' indicates canonical (immediately after the complementizer), '10n' non-canonical 
// position (anywhere else)
10: {
   10c: (CODING col 1 s)
      AND (CODING col 2 vf|auxv|vaux)
      AND (IP* idoms verb-f-all)
      AND (IP* idomsnumber 2 nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
   10n: (CODING col 1 s)
      AND (CODING col 2 vf|auxv|vaux)
      AND (IP* idoms nom-arg-usable)
   /: ELSE
}

// 11: all subjects, all clauses, pronouns can intervene
// '11c1' indicates canonical subject position; '11c2|3|4' indicates canonical except for 
// 1-3 scrambled pronouns, '11n' indicates non-canonical
// 11c3-4 not found in Beowulf
11: {
   11c1: (CODING col 1 s)
      AND (CODING col 2 vf|auxv|vaux)
      AND (IP* idoms verb-f-all)
      AND (IP* idomsnumber 2 nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
   11c2: (CODING col 1 s)
      AND (CODING col 2 vf|auxv|vaux)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms nom-arg-usable)
      AND (IP* idomsnumber 2 *)
      AND (* idomsonly PRO|PRO^*)
      AND (* iprecedes nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
// Note: no 11c3 in Beowulf
   11c3: (CODING col 1 s)
      AND (CODING col 2 vf|auxv|vaux)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms nom-arg-usable)
      AND (IP* idomsnumber 2 [1]*)
      AND ([1]* idomsonly [2]PRO|PRO^*)
      AND (IP* idomsnumber 3 [3]*)
      AND ([3]* idomsonly [4]PRO|PRO^*)
      AND ([3]* iprecedes nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
// Note: no 11c4 in Beowulf
   11c4: (CODING col 1 s)
      AND (CODING col 2 vf|auxv|vaux)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms nom-arg-usable)
      AND (IP* idomsnumber 2 [1]*)
      AND ([1]* idomsonly [2]PRO|PRO^*)
      AND (IP* idomsnumber 3 [3]*)
      AND ([3]* idomsonly [4]PRO|PRO^*)
      AND (IP* idomsnumber 4 [5]*)
      AND ([5]* idomsonly [6]PRO|PRO^*)
      AND ([5]* iprecedes nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
   11n: (CODING col 1 s)
      AND (CODING col 2 vf|auxv|vaux)
      AND (IP* idoms nom-arg-usable)
   /: ELSE
}

// 12-13: nominal subjects only, all clauses

// 12: nominal subjects, all clauses, no pronouns intervening
// '12c' indicates canonical (immediately after the complementizer), '12n' non-canonical 
// position (anywhere else)
12: {
   12c: (CODING col 1 s)
      AND (CODING col 2 vf|auxv|vaux)
      AND (IP* idoms verb-f-all)
      AND (IP* idomsnumber 2 nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
      AND (nom-arg-usable iprecedes verb-f-all)
   12n: (CODING col 1 s)
      AND (CODING col 2 vf|auxv|vaux)
      AND (IP* idoms nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
   /: ELSE
}

// 13: nominal subjects, all clauses, pronouns can intervene
// '13c1' indicates canonical subject position; '13c2|3|4' indicates canonical except for 
// 1-3 scrambled pronouns, '13n' indicates non-canonical
// Note: 13c3-4 not found in Beowulf
13: {
   13c1: (CODING col 1 s)
      AND (CODING col 2 vf|auxv|vaux)
      AND (IP* idoms verb-f-all)
      AND (IP* idomsnumber 2 nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
      AND (nom-arg-usable iprecedes verb-f-all)
   13c2: (CODING col 1 s)
      AND (CODING col 2 vf|auxv|vaux)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
      AND (IP* idomsnumber 2 *)
      AND (* idomsonly PRO|PRO^*)
      AND (* iprecedes nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
// Note: no 13c3 in Beowulf
   13c3: (CODING col 1 s)
      AND (CODING col 2 vf|auxv|vaux)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
      AND (IP* idomsnumber 2 [1]*)
      AND ([1]* idomsonly [2]PRO|PRO^*)
      AND (IP* idomsnumber 3 [3]*)
      AND ([3]* idomsonly [4]PRO|PRO^*)
      AND ([3]* iprecedes nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
// Note: no 13c4 in Beowulf
   13c4: (CODING col 1 s)
      AND (CODING col 2 vf|auxv|vaux)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
      AND (IP* idomsnumber 2 [1]*)
      AND ([1]* idomsonly [2]PRO|PRO^*)
      AND (IP* idomsnumber 3 [3]*)
      AND ([3]* idomsonly [4]PRO|PRO^*)
      AND (IP* idomsnumber 4 [5]*)
      AND ([5]* idomsonly [6]PRO|PRO^*)
      AND ([5]* iprecedes nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
   13n: (CODING col 1 s)
      AND (CODING col 2 vf|auxv|vaux)
      AND (IP* idoms nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
   /: ELSE
}

// 14-15 Pronominal and nominal subjects, head-initial IPs only
// head-initial is indicated by 1-word constituent after finite or non-finite verb

// 14 all subjects, head-initial clauses, no pronouns intervening
// '14c' indicates canonical (immediately after the complementizer), '14n' non-canonical 
// position (anywhere else)
14: {
   14c1: (CODING col 1 s)
      AND (CODING col 2 vf)
      AND (IP* idoms verb-f-all)
      AND (IP* idomsnumber 2 nom-arg-usable)
      AND (IP* idoms *)
      AND (nom-arg-usable iprecedes verb-f-all)
      AND (verb-f-all precedes *)
      AND (* domswords 1)
   14n1: (CODING col 1 s)
      AND (CODING col 2 vf)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms nom-arg-usable)
      AND (IP* idoms *)
      AND (verb-f-all precedes *)
      AND (* domswords 1)
   14c2: (CODING col 1 s)
      AND (CODING col 2 auxv)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms verb-nf-all)
      AND (IP* idoms *)
      AND (IP* idomsnumber 2 nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
      AND (verb-nf-all precedes *)
      AND (* domswords 1)
   14n2: (CODING col 1 s)
      AND (CODING col 2 auxv)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms verb-nf-all)
      AND (IP* idoms nom-arg-usable)
      AND (IP* idoms *)
      AND (verb-nf-all precedes *)
      AND (* domswords 1)
   /: ELSE
}

// 15 all subjects, head-initial clauses, pronouns can intervene
// '15c1' indicates canonical (pro|nom) subject position; 
// '15c2|3|4' indicates canonical except for 1-3 scrambled pronouns, 
// '15n' indicates non-canonical
15: {
   15c1a: (CODING col 1 s)
      AND (CODING col 2 vf)
      AND (IP* idoms verb-f-all)
      AND (IP* idomsnumber 2 nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
      AND (IP* idoms *)
      AND (* domswords 1)
      AND (verb-f-all precedes *)
   15c2a: (CODING col 1 s)
      AND (CODING col 2 vf)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms nom-arg-usable)
      AND (IP* idomsnumber 2 [1]*)
      AND ([1]* idomsonly PRO|PRO^*)
      AND ([1]* iprecedes nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
      AND (IP* idoms [2]*)
      AND ([2]* domswords 1)
      AND (verb-f-all precedes [2]*)
// Note: no 15c3a in Beowulf
   15c3a: (CODING col 1 s)
      AND (CODING col 2 vf)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms nom-arg-usable)
      AND (IP* idomsnumber 2 [1]*)
      AND ([1]* idomsonly [4]PRO|PRO^*)
      AND (IP* idoms [2]*)
      AND ([2]* idomsonly [5]PRO|PRO^*)
      AND (IP* idoms [3]*)
      AND ([3]* domswords 1)
      AND ([1]* iprecedes [2]*)
      AND ([2]* iprecedes nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
      AND (verb-f-all precedes [3]*)
   15c4a: (CODING col 1 s)
      AND (CODING col 2 vf)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms nom-arg-usable)
      AND (IP* idomsnumber 2 [1]*)
      AND ([1]* idomsonly [4]PRO|PRO^*)
      AND (IP* idoms [2]*)
      AND ([2]* idomsonly [5]PRO|PRO^*)
      AND (IP* idoms [3]*)
      AND ([3]* idomsonly [6]PRO|PRO^*)
      AND (IP* idoms [4]*)
      AND ([4]* domswords 1)
      AND ([1]* iprecedes [2]*)
      AND ([2]* iprecedes [3]*)
      AND ([3]* iprecedes nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
      AND (verb-f-all precedes [4]*)
   15c1b: (CODING col 1 s)
      AND (CODING col 2 auxv)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms verb-nf-all)
      AND (IP* idomsnumber 2 nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
      AND (IP* idoms *)
      AND (* domswords 1)
      AND (verb-nf-all precedes *)
   15c2b: (CODING col 1 s)
      AND (CODING col 2 auxv)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms verb-nf-all)
      AND (IP* idoms nom-arg-usable)
      AND (IP* idomsnumber 2 [1]*)
      AND ([1]* idomsonly PRO|PRO^*)
      AND ([1]* iprecedes nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
      AND (IP* idoms [2]*)
      AND ([2]* domswords 1)
      AND (verb-nf-all precedes [2]*)
   15c3b: (CODING col 1 s)
      AND (CODING col 2 auxv)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms verb-nf-all)
      AND (IP* idoms nom-arg-usable)
      AND (IP* idomsnumber 2 [1]*)
      AND ([1]* idomsonly [4]PRO|PRO^*)
      AND (IP* idoms [2]*)
      AND ([2]* idomsonly [5]PRO|PRO^*)
      AND (IP* idoms [3]*)
      AND ([3]* domswords 1)
      AND ([1]* iprecedes [2]*)
      AND ([2]* iprecedes nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
      AND (verb-nf-all precedes [3]*)
   15c4b: (CODING col 1 s)
      AND (CODING col 2 auxv)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms verb-nf-all)
      AND (IP* idoms nom-arg-usable)
      AND (IP* idomsnumber 2 [1]*)
      AND ([1]* idomsonly [4]PRO|PRO^*)
      AND (IP* idoms [2]*)
      AND ([2]* idomsonly [5]PRO|PRO^*)
      AND (IP* idoms [3]*)
      AND ([3]* idomsonly [6]PRO|PRO^*)
      AND (IP* idoms [4]*)
      AND ([4]* domswords 1)
      AND ([1]* iprecedes [2]*)
      AND ([2]* iprecedes [3]*)
      AND ([3]* iprecedes nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
      AND (verb-nf-all precedes [4]*)
   15n1: (CODING col 1 s)
      AND (CODING col 2 vf)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms nom-arg-usable)
      AND (IP* idoms *)
      AND (verb-f-all precedes *)
      AND (* domswords 1)
   15n2: (CODING col 1 s)
      AND (CODING col 2 auxv)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms verb-nf-all)
      AND (IP* idoms nom-arg-usable)
      AND (IP* idoms *)
      AND (verb-nf-all precedes *)
      AND (* domswords 1)
   /: ELSE
}

// 16-17 nominal subjects, head-initial IPs
// head-initial is indicated by 1-word constituent after finite or non-finite verb

// '16c' indicates canonical (immediately after the complementizer), '16n' non-canonical 
// position (anywhere else)
16: {
   16c1: (CODING col 1 s)
      AND (CODING col 2 vf)
      AND (IP* idoms verb-f-all)
      AND (IP* idomsnumber 2 nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
      AND (nom-arg-usable iprecedes verb-f-all)
      AND (IP* idoms *)
      AND (verb-f-all precedes *)
      AND (* domswords 1)
   16n1: (CODING col 1 s)
      AND (CODING col 2 vf)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
      AND (IP* idoms *)
      AND (verb-f-all precedes *)
      AND (* domswords 1)
   16c2: (CODING col 1 s)
      AND (CODING col 2 auxv)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms verb-nf-all)
      AND (IP* idomsnumber 2 nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
      AND (nom-arg-usable iprecedes verb-f-all)
      AND (IP* idoms *)
      AND (verb-nf-all precedes *)
      AND (* domswords 1)
   16n2: (CODING col 1 s)
      AND (CODING col 2 auxv)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms verb-nf-all)
      AND (IP* idoms nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
      AND (IP* idoms *)
      AND (verb-nf-all precedes *)
      AND (* domswords 1)
   /: ELSE
}

// '17c1' indicates canonical (pro|nom) subject position; 
// '17c2|3|4' indicates canonical except for 1-3 scrambled pronouns, 
// '17n' indicates non-canonical
17: {
   17c1a: (CODING col 1 s)
      AND (CODING col 2 vf)
      AND (IP* idoms verb-f-all)
      AND (IP* idomsnumber 2 nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
      AND (nom-arg-usable iprecedes verb-f-all)
      AND (IP* idoms *)
      AND (* domswords 1)
      AND (verb-f-all precedes *)
   17c2a: (CODING col 1 s)
      AND (CODING col 2 vf)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
      AND (IP* idomsnumber 2 [1]*)
      AND ([1]* idomsonly PRO|PRO^*)
      AND ([1]* iprecedes nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
      AND (IP* idoms [2]*)
      AND ([2]* domswords 1)
      AND (verb-f-all precedes [2]*)
   17c3a: (CODING col 1 s)
      AND (CODING col 2 vf)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
      AND (IP* idomsnumber 2 [1]*)
      AND ([1]* idomsonly [4]PRO|PRO^*)
      AND (IP* idoms [2]*)
      AND ([2]* idomsonly [5]PRO|PRO^*)
      AND (IP* idoms [3]*)
      AND ([3]* domswords 1)
      AND ([1]* iprecedes [2]*)
      AND ([2]* iprecedes nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
      AND (verb-f-all precedes [3]*)
   17c4a: (CODING col 1 s)
      AND (CODING col 2 vf)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
      AND (IP* idomsnumber 2 [1]*)
      AND ([1]* idomsonly [4]PRO|PRO^*)
      AND (IP* idoms [2]*)
      AND ([2]* idomsonly [5]PRO|PRO^*)
      AND (IP* idoms [3]*)
      AND ([3]* idomsonly [6]PRO|PRO^*)
      AND (IP* idoms [4]*)
      AND ([4]* domswords 1)
      AND ([1]* iprecedes [2]*)
      AND ([2]* iprecedes [3]*)
      AND ([3]* iprecedes nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
      AND (verb-f-all precedes [4]*)
   17c1b: (CODING col 1 s)
      AND (CODING col 2 auxv)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms verb-nf-all)
      AND (IP* idomsnumber 2 nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
      AND (IP* idoms *)
      AND (* domswords 1)
      AND (verb-nf-all precedes *)
   17c2b: (CODING col 1 s)
      AND (CODING col 2 auxv)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms verb-nf-all)
      AND (IP* idoms nom-arg-usable)
      AND (IP* idomsnumber 2 [1]*)
      AND ([1]* idomsonly PRO|PRO^*)
      AND ([1]* iprecedes nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
      AND (nom-arg-usable iprecedes verb-f-all)
      AND (IP* idoms [2]*)
      AND ([2]* domswords 1)
      AND (verb-nf-all precedes [2]*)
   17c3b: (CODING col 1 s)
      AND (CODING col 2 auxv)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms verb-nf-all)
      AND (IP* idoms nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
      AND (IP* idomsnumber 2 [1]*)
      AND ([1]* idomsonly [4]PRO|PRO^*)
      AND (IP* idoms [2]*)
      AND ([2]* idomsonly [5]PRO|PRO^*)
      AND (IP* idoms [3]*)
      AND ([3]* domswords 1)
      AND ([1]* iprecedes [2]*)
      AND ([2]* iprecedes nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
      AND (verb-nf-all precedes [3]*)
   17c4b: (CODING col 1 s)
      AND (CODING col 2 auxv)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms verb-nf-all)
      AND (IP* idoms nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
      AND (IP* idomsnumber 2 [1]*)
      AND ([1]* idomsonly [4]PRO|PRO^*)
      AND (IP* idoms [2]*)
      AND ([2]* idomsonly [5]PRO|PRO^*)
      AND (IP* idoms [3]*)
      AND ([3]* idomsonly [6]PRO|PRO^*)
      AND (IP* idoms [4]*)
      AND ([4]* domswords 1)
      AND ([1]* iprecedes [2]*)
      AND ([2]* iprecedes [3]*)
      AND ([3]* iprecedes nom-arg-usable)
      AND (nom-arg-usable iprecedes verb-f-all)
      AND (verb-nf-all precedes [4]*)
   17n1: (CODING col 1 s)
      AND (CODING col 2 vf)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
      AND (IP* idoms *)
      AND (verb-f-all precedes *)
      AND (* domswords 1)
   17n2: (CODING col 1 s)
      AND (CODING col 2 auxv)
      AND (IP* idoms verb-f-all)
      AND (IP* idoms verb-nf-all)
      AND (IP* idoms nom-arg-usable)
      AND (nom-arg-usable idoms non-pronominal)
      AND (IP* idoms *)
      AND (verb-nf-all precedes *)
      AND (* domswords 1)
   /: ELSE
}
